### ISSUE TITLE
Gitako isn't available in the Chrome web store which causes the generate task to fail

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#1087]
I'm not sure where in the generate process this should be handled now, but https://github.com/EnixCoda/Gitako isn't listed in the Chrome web store right now (probably for similar reasons as Stylus recently had). So now when you try to run `npm run generate` it fails on this item. This might be why we haven't had automated releases the last few days as well.

```
Unhandled rejection Error: FILE_ENDED
    at PullStream.pull (C:\dev\GitHub\GitHub-Dark\node_modules\unzipper\lib\PullStream.js:83:28)
    at PullStream.emit (events.js:210:5)
    at PullStream.<anonymous> (C:\dev\GitHub\GitHub-Dark\node_modules\unzipper\lib\PullStream.js:20:10)
    at PullStream.emit (events.js:215:7)
    at finishMaybe (_stream_writable.js:656:14)
    at endWritable (_stream_writable.js:673:3)
    at PullStream.Writable.end (_stream_writable.js:604:5)
    at PassThrough.onend (_stream_readable.js:691:10)
    at Object.onceWrapper (events.js:299:28)
    at PassThrough.emit (events.js:210:5)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by the-j0k3r** [comment]
Lat release 3 days ago, but if its an issue will be temporary why not comment it out for now, that is until generator can handle the failure in a better way.

**Comment by xt0rted** [comment]
The fix is in one of @silverwind's packages so I'll let him decide how best to do that. The issue with commenting this out is it removes all the existing rules so anyone using this extension loses styling completely.

**Comment by silverwind** [comment]
The download failed with `204` status code, that's why it did not throw earlier and ran into the unzipping error. I changed it so it will just continue and return empty CSS if the download fails for whatever reason. This will produce a warning log:

```
(remap-css) Warning: Unexpected status code 204 for extension giljefjcheohhamkjphiebfjnlphnokk
```

Once the extension returns to the store, it should automatically fix itself.

**Comment by xt0rted** [comment]
Nice to see they use a success status code instead of a 404 🙄

**Comment by silverwind** [comment]
Yeah, the only time where it's correct to send a `204` is in response to a `DELETE`. 😉

Writing warnings to stderr is probably not the best way of communicating them, I'll think about something that can be consumed via the API.
